
backend:
  name: git-gateway
  branch: main

media_folder: "assets"
public_folder: "/assets"

collections:
  - name: "rooms"
    label: "Rooms"
    folder: "content/rooms"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Room Name", name: "name", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }
